yolo_model:

  config_file:
    name: yolov3-ycb.cfg
  weight_file:
    name: yolov3-ycb_best.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - cracker
      - sugar
      - pudding
      - gelatin
      - pottedmeat
      - coffee
      - tuna
      - chips
      - mustard
      - tomatosoup
      - banana
      - strawberry
      - apple
      - lemon
      - peach
      - pear
      - orange
      - plum
      - windex
      - bleach
      - pitcher
      - plate
      - bowl
      - fork
      - spoon
      - spatula
      - wineglass
      - mug
      - largemarker
      - smallmarker
      - keys
      - bolt
      - nut
      - clamp
      - soccerball
      - baseball
      - tennisball
      - golfball
      - foam
      - dice
      - rope
      - chain
      - rubikscube
      - coloredwoodblock
      - peghole
      - timer
      - airplane
      - tshirt
      - magazine
      - creditcard
      - legoduplo